# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ekf_rio/EkfRioState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class EkfRioState(genpy.Message):
  _md5sum = "6c5323fa7187f2894466fea406ae0fd2"
  _type = "ekf_rio/EkfRioState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

geometry_msgs/Vector3 p
geometry_msgs/Vector3 v
geometry_msgs/Quaternion q
geometry_msgs/Vector3 eul_deg
geometry_msgs/Vector3 b_a
geometry_msgs/Vector3 b_g_deg
float32 b_alt
geometry_msgs/Vector3 l_b_r
geometry_msgs/Quaternion q_b_r
geometry_msgs/Vector3 eul_b_r_deg


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','p','v','q','eul_deg','b_a','b_g_deg','b_alt','l_b_r','q_b_r','eul_b_r_deg']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','float32','geometry_msgs/Vector3','geometry_msgs/Quaternion','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,p,v,q,eul_deg,b_a,b_g_deg,b_alt,l_b_r,q_b_r,eul_b_r_deg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EkfRioState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.p is None:
        self.p = geometry_msgs.msg.Vector3()
      if self.v is None:
        self.v = geometry_msgs.msg.Vector3()
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.eul_deg is None:
        self.eul_deg = geometry_msgs.msg.Vector3()
      if self.b_a is None:
        self.b_a = geometry_msgs.msg.Vector3()
      if self.b_g_deg is None:
        self.b_g_deg = geometry_msgs.msg.Vector3()
      if self.b_alt is None:
        self.b_alt = 0.
      if self.l_b_r is None:
        self.l_b_r = geometry_msgs.msg.Vector3()
      if self.q_b_r is None:
        self.q_b_r = geometry_msgs.msg.Quaternion()
      if self.eul_b_r_deg is None:
        self.eul_b_r_deg = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.p = geometry_msgs.msg.Vector3()
      self.v = geometry_msgs.msg.Vector3()
      self.q = geometry_msgs.msg.Quaternion()
      self.eul_deg = geometry_msgs.msg.Vector3()
      self.b_a = geometry_msgs.msg.Vector3()
      self.b_g_deg = geometry_msgs.msg.Vector3()
      self.b_alt = 0.
      self.l_b_r = geometry_msgs.msg.Vector3()
      self.q_b_r = geometry_msgs.msg.Quaternion()
      self.eul_b_r_deg = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_19df10d().pack(_x.p.x, _x.p.y, _x.p.z, _x.v.x, _x.v.y, _x.v.z, _x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.eul_deg.x, _x.eul_deg.y, _x.eul_deg.z, _x.b_a.x, _x.b_a.y, _x.b_a.z, _x.b_g_deg.x, _x.b_g_deg.y, _x.b_g_deg.z, _x.b_alt, _x.l_b_r.x, _x.l_b_r.y, _x.l_b_r.z, _x.q_b_r.x, _x.q_b_r.y, _x.q_b_r.z, _x.q_b_r.w, _x.eul_b_r_deg.x, _x.eul_b_r_deg.y, _x.eul_b_r_deg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.p is None:
        self.p = geometry_msgs.msg.Vector3()
      if self.v is None:
        self.v = geometry_msgs.msg.Vector3()
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.eul_deg is None:
        self.eul_deg = geometry_msgs.msg.Vector3()
      if self.b_a is None:
        self.b_a = geometry_msgs.msg.Vector3()
      if self.b_g_deg is None:
        self.b_g_deg = geometry_msgs.msg.Vector3()
      if self.l_b_r is None:
        self.l_b_r = geometry_msgs.msg.Vector3()
      if self.q_b_r is None:
        self.q_b_r = geometry_msgs.msg.Quaternion()
      if self.eul_b_r_deg is None:
        self.eul_b_r_deg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 236
      (_x.p.x, _x.p.y, _x.p.z, _x.v.x, _x.v.y, _x.v.z, _x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.eul_deg.x, _x.eul_deg.y, _x.eul_deg.z, _x.b_a.x, _x.b_a.y, _x.b_a.z, _x.b_g_deg.x, _x.b_g_deg.y, _x.b_g_deg.z, _x.b_alt, _x.l_b_r.x, _x.l_b_r.y, _x.l_b_r.z, _x.q_b_r.x, _x.q_b_r.y, _x.q_b_r.z, _x.q_b_r.w, _x.eul_b_r_deg.x, _x.eul_b_r_deg.y, _x.eul_b_r_deg.z,) = _get_struct_19df10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_19df10d().pack(_x.p.x, _x.p.y, _x.p.z, _x.v.x, _x.v.y, _x.v.z, _x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.eul_deg.x, _x.eul_deg.y, _x.eul_deg.z, _x.b_a.x, _x.b_a.y, _x.b_a.z, _x.b_g_deg.x, _x.b_g_deg.y, _x.b_g_deg.z, _x.b_alt, _x.l_b_r.x, _x.l_b_r.y, _x.l_b_r.z, _x.q_b_r.x, _x.q_b_r.y, _x.q_b_r.z, _x.q_b_r.w, _x.eul_b_r_deg.x, _x.eul_b_r_deg.y, _x.eul_b_r_deg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.p is None:
        self.p = geometry_msgs.msg.Vector3()
      if self.v is None:
        self.v = geometry_msgs.msg.Vector3()
      if self.q is None:
        self.q = geometry_msgs.msg.Quaternion()
      if self.eul_deg is None:
        self.eul_deg = geometry_msgs.msg.Vector3()
      if self.b_a is None:
        self.b_a = geometry_msgs.msg.Vector3()
      if self.b_g_deg is None:
        self.b_g_deg = geometry_msgs.msg.Vector3()
      if self.l_b_r is None:
        self.l_b_r = geometry_msgs.msg.Vector3()
      if self.q_b_r is None:
        self.q_b_r = geometry_msgs.msg.Quaternion()
      if self.eul_b_r_deg is None:
        self.eul_b_r_deg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 236
      (_x.p.x, _x.p.y, _x.p.z, _x.v.x, _x.v.y, _x.v.z, _x.q.x, _x.q.y, _x.q.z, _x.q.w, _x.eul_deg.x, _x.eul_deg.y, _x.eul_deg.z, _x.b_a.x, _x.b_a.y, _x.b_a.z, _x.b_g_deg.x, _x.b_g_deg.y, _x.b_g_deg.z, _x.b_alt, _x.l_b_r.x, _x.l_b_r.y, _x.l_b_r.z, _x.q_b_r.x, _x.q_b_r.y, _x.q_b_r.z, _x.q_b_r.w, _x.eul_b_r_deg.x, _x.eul_b_r_deg.y, _x.eul_b_r_deg.z,) = _get_struct_19df10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_19df10d = None
def _get_struct_19df10d():
    global _struct_19df10d
    if _struct_19df10d is None:
        _struct_19df10d = struct.Struct("<19df10d")
    return _struct_19df10d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
